# Example: the pipeline from the specification, in full (explicit) form.
[bv:BV1TqaR67E7f] -> band-roformer[msst:Kim_MelBandRoformer.ckpt]
[var:band-roformer] -> vocals[unzip:vocals.wav]
[var:vocals] -> karaoke-roformer[msst:bs_roformer_karaoke_frazer_becruily.ckpt]
[var:karaoke-roformer] -> vocal[unzip:Vocals.wav]
[var:vocal] -> mono-vocal[audio:mono]
[var:mono-vocal] -> dereverb-vocal[msst:dereverb_room_anvuew_sdr_13.7432.ckpt]
[var:dereverb-vocal] -> noreverb-vocal[unzip:noreverb]
[var:noreverb-vocal] -> viridis-vocal[rvc:viridis-v2_200e_5000s.pth]
[var:viridis-vocal] -> reverb-viridis-vocal[audio:reverb]
[var:band-roformer] -> bands[unzip:other.wav]
[var:karaoke-roformer] -> harmony[unzip:Instrumental.wav]
[var:viridis-vocal, bands, harmony] -> result[audio:mix]
[var:result] -> [final]
